/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Neto
 */
public class FormDialogLivro extends javax.swing.JDialog {

    /**
     * Creates new form FormDialogLivro
     */
    public FormDialogLivro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNovoFormLivro = new javax.swing.JButton();
        jButtonSalvarFormLivro = new javax.swing.JButton();
        jButtonExcluirFormLivro = new javax.swing.JButton();
        jButtonPesquisarLivro = new javax.swing.JButton();
        jTextFieldPesquisarAluno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListagemLivros = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldIdLivro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jButtonNovoFormLivro.setText("Novo");
        jButtonNovoFormLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoFormLivroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovoFormLivro);
        jButtonNovoFormLivro.setBounds(870, 380, 80, 30);

        jButtonSalvarFormLivro.setText("Salvar");
        jButtonSalvarFormLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarFormLivroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvarFormLivro);
        jButtonSalvarFormLivro.setBounds(870, 330, 80, 30);

        jButtonExcluirFormLivro.setText("Excluir");
        jButtonExcluirFormLivro.setEnabled(false);
        jButtonExcluirFormLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirFormLivroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluirFormLivro);
        jButtonExcluirFormLivro.setBounds(870, 430, 80, 30);

        jButtonPesquisarLivro.setText("Pesquisar");
        jButtonPesquisarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarLivroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisarLivro);
        jButtonPesquisarLivro.setBounds(610, 40, 90, 30);

        jTextFieldPesquisarAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarAlunoKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldPesquisarAluno);
        jTextFieldPesquisarAluno.setBounds(140, 40, 430, 31);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pesquisar Livro: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 50, 120, 20);

        jTableListagemLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListagemLivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListagemLivros);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 1040, 220);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Código do Livro:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 330, 120, 30);

        jTextFieldIdLivro.setEnabled(false);
        jPanel1.add(jTextFieldIdLivro);
        jTextFieldIdLivro.setBounds(250, 330, 240, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Livros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(388, 388, 388))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoFormLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoFormLivroActionPerformed
        //this.limparCampos();
        jButtonExcluirFormLivro.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoFormLivroActionPerformed

    private void jButtonSalvarFormLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarFormLivroActionPerformed
        if(jTextFieldIdLivro.getText().equals("")){
            //this.insert();

        } else {
            //this.update();
        }

        /*
        try {
            tabelaAlunos.setResult(select());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }*/
    }//GEN-LAST:event_jButtonSalvarFormLivroActionPerformed

    private void jButtonExcluirFormLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirFormLivroActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this,
            "Tem certeza que você deseja excluir esse registro?",
            "Exclusão de Cadastro",
            JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            
        }
    }//GEN-LAST:event_jButtonExcluirFormLivroActionPerformed

    private void jButtonPesquisarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarLivroActionPerformed
       

    }//GEN-LAST:event_jButtonPesquisarLivroActionPerformed

    private void jTextFieldPesquisarAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarAlunoKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
        }
    }//GEN-LAST:event_jTextFieldPesquisarAlunoKeyReleased

    private void jTableListagemLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListagemLivrosMouseClicked
        jTextFieldIdLivro.setText(jTableListagemLivros.getValueAt(jTableListagemLivros.getSelectedRow(), 0).toString());
        

        jButtonExcluirFormLivro.setEnabled(true);

    }//GEN-LAST:event_jTableListagemLivrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDialogLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDialogLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDialogLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDialogLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormDialogLivro dialog = new FormDialogLivro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluirFormLivro;
    private javax.swing.JButton jButtonNovoFormLivro;
    private javax.swing.JButton jButtonPesquisarLivro;
    private javax.swing.JButton jButtonSalvarFormLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListagemLivros;
    private javax.swing.JTextField jTextFieldIdLivro;
    private javax.swing.JTextField jTextFieldPesquisarAluno;
    // End of variables declaration//GEN-END:variables
}
